name: dart_mappable_workspace
publish_to: none

environment:
  sdk: '>=3.7.0 <4.0.0'

workspace:
  - packages/dart_mappable
  - packages/dart_mappable_builder

dev_dependencies:
  melos: ^7.0.0

melos:
  ide:
    intellij:
      enabled: false
      
  command:
    bootstrap:
      usePubspecOverrides: true

  scripts:
    test:
      run: dart test
      exec:
        concurrency: 1
      packageFilters:
        scope:
          - dart_mappable
          - dart_mappable_builder
          - package_comparison
    coverage:
      run: |
        dart test --coverage=coverage &&
        dart pub global run coverage:format_coverage --check-ignore --report-on=lib --lcov -o "$MELOS_ROOT_PATH/coverage/\$MELOS_PACKAGE_NAME_lcov.info" -i ./coverage
      exec:
        concurrency: 1
      packageFilters:
        scope: 
          - dart_mappable
          - dart_mappable_builder
    build:
      exec: dart run build_runner build -d
      packageFilters:
        scope:
    format:
      exec: dart format . --set-exit-if-changed
    analyze:
      exec: dart analyze . --fatal-infos
