// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element

import '../../example/lib/main.dart' as p0;
import '../copy_with/copy_with_data_test.dart' as p3;
import '../copy_with/copy_with_subtype_test.dart' as p4;
import '../copy_with/copy_with_test.dart' as p5;
import '../custom_mapper/custom_mapper_test.dart' as p6;
import '../enums/enum_map_test.dart' as p7;
import '../enums/enums_test.dart' as p8;
import '../generics/duplicate_names_test.dart' as p9;
import '../generics/generics_change_test.dart' as p10;
import '../generics/generics_test.dart' as p11;
import '../hooks/hooks_test.dart' as p12;
import '../lib_mapping/lib_mapping_test.dart' as p13;
import '../polymorphism/custom_discriminator_test.dart' as p14;
import '../polymorphism/mixed_mappable_test.dart' as p15;
import '../polymorphism/multi_poly_test.dart' as p16;
import '../polymorphism/polymorphism_test.dart' as p17;
import '../primitives/primitives_test.dart' as p18;
import '../selective_generation/selective_generation_test.dart' as p19;
import '../serialization/basic_serialization_test.dart' as p20;
import '../serialization/model.dart' as p21;
import '../serialization/nested_serialization_test.dart' as p22;
import 'init_lib_test.dart' as p1;
import 'models/model.dart' as p2;

void initializeMappers() {
  p0.PersonMapper.ensureInitialized();
  p0.CarMapper.ensureInitialized();
  p0.BoxMapper.ensureInitialized();
  p0.ConfettiMapper.ensureInitialized();
  p0.BrandMapper.ensureInitialized();
  p1.AMapper.ensureInitialized();
  p1.BMapper.ensureInitialized();
  p2.AMapper.ensureInitialized();
  p3.AMapper.ensureInitialized();
  p3.BMapper.ensureInitialized();
  p4.AnimalMapper.ensureInitialized();
  p4.CatMapper.ensureInitialized();
  p4.DogMapper.ensureInitialized();
  p4.ZooMapper.ensureInitialized();
  p4.AMapper.ensureInitialized();
  p4.CMapper.ensureInitialized();
  p4.BMapper.ensureInitialized();
  p5.PersonMapper.ensureInitialized();
  p5.CarMapper.ensureInitialized();
  p5.BrandMapper.ensureInitialized();
  p5.DealershipMapper.ensureInitialized();
  p5.ItemListMapper.ensureInitialized();
  p5.BrandListMapper.ensureInitialized();
  p5.NamedItemListMapper.ensureInitialized();
  p5.KeyedItemListMapper.ensureInitialized();
  p5.ComparableItemListMapper.ensureInitialized();
  p6.TestObjMapper.ensureInitialized();
  p7.ClassAMapper.ensureInitialized();
  p7.EnumAMapper.ensureInitialized();
  p8.StateMapper.ensureInitialized();
  p8.ColorMapper.ensureInitialized();
  p8.ItemsMapper.ensureInitialized();
  p8.StatusMapper.ensureInitialized();
  p9.BoxMapper.ensureInitialized();
  p9.ContentMapper.ensureInitialized();
  p10.AMapper.ensureInitialized();
  p10.BMapper.ensureInitialized();
  p10.CMapper.ensureInitialized();
  p10.DMapper.ensureInitialized();
  p10.EMapper.ensureInitialized();
  p11.BoxMapper.ensureInitialized();
  p11.ConfettiMapper.ensureInitialized();
  p11.ContentMapper.ensureInitialized();
  p11.DataMapper.ensureInitialized();
  p11.SingleSettingMapper.ensureInitialized();
  p11.SettingsMapper.ensureInitialized();
  p11.AssetMapper.ensureInitialized();
  p12.GameMapper.ensureInitialized();
  p12.CardGameMapper.ensureInitialized();
  p12.PlayerMapper.ensureInitialized();
  p12.ClothesMapper.ensureInitialized();
  p12.ComponentMapper.ensureInitialized();
  p13.PersonMapper.ensureInitialized();
  p14.AMapper.ensureInitialized();
  p14.BMapper.ensureInitialized();
  p14.CMapper.ensureInitialized();
  p15.BaseMapper.ensureInitialized();
  p15.OneMapper.ensureInitialized();
  p15.TwoMapper.ensureInitialized();
  p16.AnimalMapper.ensureInitialized();
  p16.CatMapper.ensureInitialized();
  p16.SiameseMapper.ensureInitialized();
  p16.DogMapper.ensureInitialized();
  p16.ShepherdMapper.ensureInitialized();
  p17.AnimalMapper.ensureInitialized();
  p17.CatMapper.ensureInitialized();
  p17.DogMapper.ensureInitialized();
  p17.NullAnimalMapper.ensureInitialized();
  p17.DefaultAnimalMapper.ensureInitialized();
  p17.ZooMapper.ensureInitialized();
  p18.ItemsMapper.ensureInitialized();
  p18.ItemMapper.ensureInitialized();
  p19.AMapper.ensureInitialized();
  p19.BMapper.ensureInitialized();
  p20.AMapper.ensureInitialized();
  p21.BMapper.ensureInitialized();
  p22.PersonMapper.ensureInitialized();
  p22.CarMapper.ensureInitialized();
  p22.BrandMapper.ensureInitialized();
}
