// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element

import '../../example/lib/main.dart' as p0;
import '../copy_with/copy_with_2_test.dart' as p3;
import '../copy_with/copy_with_test.dart' as p4;
import '../custom_mapper/custom_mapper_test.dart' as p5;
import '../enums/enum_map_test.dart' as p6;
import '../enums/enums_test.dart' as p7;
import '../generics/duplicate_names_test.dart' as p8;
import '../generics/generics_change_test.dart' as p9;
import '../generics/generics_test.dart' as p10;
import '../hooks/hooks_test.dart' as p11;
import '../lib_mapping/lib_mapping_test.dart' as p12;
import '../polymorphism/custom_discriminator_test.dart' as p13;
import '../polymorphism/mixed_mappable_test.dart' as p14;
import '../polymorphism/multi_poly_test.dart' as p15;
import '../polymorphism/polymorphism_test.dart' as p16;
import '../primitives/primitives_test.dart' as p17;
import '../selective_generation/selective_generation_test.dart' as p18;
import '../serialization/basic_serialization_test.dart' as p19;
import '../serialization/model.dart' as p20;
import '../serialization/nested_serialization_test.dart' as p21;
import 'init_lib_test.dart' as p1;
import 'models/model.dart' as p2;

void initializeMappers() {
  p0.PersonMapper.ensureInitialized();
  p0.CarMapper.ensureInitialized();
  p0.BoxMapper.ensureInitialized();
  p0.ConfettiMapper.ensureInitialized();
  p0.BrandMapper.ensureInitialized();
  p1.AMapper.ensureInitialized();
  p1.BMapper.ensureInitialized();
  p2.AMapper.ensureInitialized();
  p3.AnimalMapper.ensureInitialized();
  p3.CatMapper.ensureInitialized();
  p3.DogMapper.ensureInitialized();
  p3.ZooMapper.ensureInitialized();
  p3.AMapper.ensureInitialized();
  p3.CMapper.ensureInitialized();
  p3.BMapper.ensureInitialized();
  p4.PersonMapper.ensureInitialized();
  p4.CarMapper.ensureInitialized();
  p4.BrandMapper.ensureInitialized();
  p4.DealershipMapper.ensureInitialized();
  p4.ItemListMapper.ensureInitialized();
  p4.BrandListMapper.ensureInitialized();
  p4.NamedItemListMapper.ensureInitialized();
  p4.KeyedItemListMapper.ensureInitialized();
  p4.ComparableItemListMapper.ensureInitialized();
  p5.TestObjMapper.ensureInitialized();
  p6.ClassAMapper.ensureInitialized();
  p6.EnumAMapper.ensureInitialized();
  p7.StateMapper.ensureInitialized();
  p7.ColorMapper.ensureInitialized();
  p7.ItemsMapper.ensureInitialized();
  p7.StatusMapper.ensureInitialized();
  p8.BoxMapper.ensureInitialized();
  p8.ContentMapper.ensureInitialized();
  p9.AMapper.ensureInitialized();
  p9.BMapper.ensureInitialized();
  p9.CMapper.ensureInitialized();
  p9.DMapper.ensureInitialized();
  p9.EMapper.ensureInitialized();
  p10.BoxMapper.ensureInitialized();
  p10.ConfettiMapper.ensureInitialized();
  p10.ContentMapper.ensureInitialized();
  p10.DataMapper.ensureInitialized();
  p10.SingleSettingMapper.ensureInitialized();
  p10.SettingsMapper.ensureInitialized();
  p10.AssetMapper.ensureInitialized();
  p11.GameMapper.ensureInitialized();
  p11.CardGameMapper.ensureInitialized();
  p11.PlayerMapper.ensureInitialized();
  p11.ClothesMapper.ensureInitialized();
  p11.ComponentMapper.ensureInitialized();
  p12.PersonMapper.ensureInitialized();
  p13.AMapper.ensureInitialized();
  p13.BMapper.ensureInitialized();
  p13.CMapper.ensureInitialized();
  p14.BaseMapper.ensureInitialized();
  p14.OneMapper.ensureInitialized();
  p14.TwoMapper.ensureInitialized();
  p15.AnimalMapper.ensureInitialized();
  p15.CatMapper.ensureInitialized();
  p15.SiameseMapper.ensureInitialized();
  p15.DogMapper.ensureInitialized();
  p15.ShepherdMapper.ensureInitialized();
  p16.AnimalMapper.ensureInitialized();
  p16.CatMapper.ensureInitialized();
  p16.DogMapper.ensureInitialized();
  p16.NullAnimalMapper.ensureInitialized();
  p16.DefaultAnimalMapper.ensureInitialized();
  p16.ZooMapper.ensureInitialized();
  p17.ItemsMapper.ensureInitialized();
  p17.ItemMapper.ensureInitialized();
  p18.AMapper.ensureInitialized();
  p18.BMapper.ensureInitialized();
  p19.AMapper.ensureInitialized();
  p20.BMapper.ensureInitialized();
  p21.PersonMapper.ensureInitialized();
  p21.CarMapper.ensureInitialized();
  p21.BrandMapper.ensureInitialized();
}
