include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true

linter:
  rules:
    sort_pub_dependencies: true
    prefer_relative_imports: true
    prefer_single_quotes: true
    depend_on_referenced_packages: true
