name: dart_mappable_schema
description: Generate JSON Schema from dart_mappable models and utilities to work with those schemas.
version: 0.1.0
repository: https://github.com/schultek/dart_mappable
issue_tracker: https://github.com/schultek/dart_mappable/issues
documentation: https://pub.dev/documentation/dart_mappable/latest/topics/Introduction-topic.html
funding:
  - https://github.com/sponsors/schultek

environment:
  sdk: '>=3.7.0 <4.0.0'

topics:
  - json
  - json-schema
  - codegen
  - dart

dependencies:
  dart_mappable: ^4.6.0
  meta: ^1.8.0
  type_plus: ^2.1.1

dev_dependencies:
  build_runner: ^2.4.14
  dart_mappable_builder: ^4.6.0
  lints: ^5.0.0
  test: ^1.25.10
