// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element

import '../../example/lib/main.dart' as p0;
import '../copy_with/collection_copy_with_test.dart' as p1;
import '../copy_with/copy_with_data_test.dart' as p2;
import '../copy_with/copy_with_generic_poly_test.dart' as p3;
import '../copy_with/copy_with_subtype_test.dart' as p4;
import '../copy_with/copy_with_test.dart' as p5;
import '../copy_with/interface_copy_with.dart' as p6;
import '../copy_with/retype_copy_with.dart' as p7;
import '../custom_mapper/custom_mapper_test.dart' as p8;
import '../enums/enum_map_test.dart' as p9;
import '../enums/enums_test.dart' as p10;
import '../equality/class_equality.dart' as p11;
import '../equality/collection_equality_test.dart' as p12;
import '../external_types/external_types_test.dart' as p13;
import '../external_types/unknown_interface.dart' as p14;
import '../generics/duplicate_names_test.dart' as p15;
import '../generics/generics_change_test.dart' as p16;
import '../generics/generics_test.dart' as p17;
import '../hooks/hooks_test.dart' as p18;
import '../hooks/string_hooks_test.dart' as p19;
import '../hooks/unmapped_props_hook_test.dart' as p20;
import '../polymorphism/custom_discriminator_test.dart' as p23;
import '../polymorphism/mixed_mappable_test.dart' as p24;
import '../polymorphism/multi_poly_test.dart' as p25;
import '../polymorphism/polymorphism_test.dart' as p26;
import '../primitives/primitives_test.dart' as p27;
import '../records/mappable_record_test.dart' as p28;
import '../records/record_model_test.dart' as p29;
import '../selective_generation/selective_generation_test.dart' as p30;
import '../serialization/basic_serialization_test.dart' as p31;
import '../serialization/desync_serialization_test.dart' as p32;
import '../serialization/nested_serialization_test.dart' as p33;
import '../serialization/param_rewrite_test.dart' as p34;
import 'init_lib_test.dart' as p21;
import 'models/model.dart' as p22;

void initializeMappers() {
  p0.PersonMapper.ensureInitialized();
  p0.CarMapper.ensureInitialized();
  p0.BoxMapper.ensureInitialized();
  p0.ConfettiMapper.ensureInitialized();
  p0.BrandMapper.ensureInitialized();
  p1.AMapper.ensureInitialized();
  p1.BMapper.ensureInitialized();
  p2.AMapper.ensureInitialized();
  p2.BMapper.ensureInitialized();
  p3.AMapper.ensureInitialized();
  p3.BMapper.ensureInitialized();
  p3.CMapper.ensureInitialized();
  p3.DMapper.ensureInitialized();
  p4.AnimalMapper.ensureInitialized();
  p4.CatMapper.ensureInitialized();
  p4.DogMapper.ensureInitialized();
  p4.ZooMapper.ensureInitialized();
  p4.AMapper.ensureInitialized();
  p4.CMapper.ensureInitialized();
  p4.BMapper.ensureInitialized();
  p5.PersonMapper.ensureInitialized();
  p5.CarMapper.ensureInitialized();
  p5.BrandMapper.ensureInitialized();
  p5.DealershipMapper.ensureInitialized();
  p5.ItemListMapper.ensureInitialized();
  p5.BrandListMapper.ensureInitialized();
  p5.NamedItemListMapper.ensureInitialized();
  p5.KeyedItemListMapper.ensureInitialized();
  p5.ComparableItemListMapper.ensureInitialized();
  p6.AMapper.ensureInitialized();
  p6.BMapper.ensureInitialized();
  p6.CMapper.ensureInitialized();
  p7.AMapper.ensureInitialized();
  p7.BMapper.ensureInitialized();
  p7.VMapper.ensureInitialized();
  p7.WMapper.ensureInitialized();
  p8.TestObjMapper.ensureInitialized();
  p9.ClassAMapper.ensureInitialized();
  p9.EnumAMapper.ensureInitialized();
  p10.StateMapper.ensureInitialized();
  p10.ColorMapper.ensureInitialized();
  p10.ItemsMapper.ensureInitialized();
  p10.StatusMapper.ensureInitialized();
  p11.AMapper.ensureInitialized();
  p11.BaseMapper.ensureInitialized();
  p11.SubMapper.ensureInitialized();
  p11.BaseTypeMapper.ensureInitialized();
  p11.SubTypeMapper.ensureInitialized();
  p11.GenericMapper.ensureInitialized();
  p11.WrapperMapper.ensureInitialized();
  p11.BMapper.ensureInitialized();
  p12.SetWrapperMapper.ensureInitialized();
  p12.ListWrapperMapper.ensureInitialized();
  p12.MapWrapperMapper.ensureInitialized();
  p13.PersonMapper.ensureInitialized();
  p14.DSOpacityDataMapper.ensureInitialized();
  p14.HOpacityMapper.ensureInitialized();
  p15.BoxMapper.ensureInitialized();
  p15.ContentMapper.ensureInitialized();
  p16.AMapper.ensureInitialized();
  p16.BMapper.ensureInitialized();
  p16.CMapper.ensureInitialized();
  p16.DMapper.ensureInitialized();
  p16.EMapper.ensureInitialized();
  p16.FMapper.ensureInitialized();
  p16.GMapper.ensureInitialized();
  p16.HMapper.ensureInitialized();
  p16.IMapper.ensureInitialized();
  p16.JMapper.ensureInitialized();
  p17.BoxMapper.ensureInitialized();
  p17.ConfettiMapper.ensureInitialized();
  p17.ContentMapper.ensureInitialized();
  p17.DataMapper.ensureInitialized();
  p17.SingleSettingMapper.ensureInitialized();
  p17.SettingsMapper.ensureInitialized();
  p17.AMapper.ensureInitialized();
  p17.BMapper.ensureInitialized();
  p17.AssetMapper.ensureInitialized();
  p18.GameMapper.ensureInitialized();
  p18.CardGameMapper.ensureInitialized();
  p18.PlayerMapper.ensureInitialized();
  p19.AMapper.ensureInitialized();
  p20.AMapper.ensureInitialized();
  p21.AMapper.ensureInitialized();
  p21.BMapper.ensureInitialized();
  p22.AMapper.ensureInitialized();
  p23.AMapper.ensureInitialized();
  p23.BMapper.ensureInitialized();
  p23.CMapper.ensureInitialized();
  p24.BaseMapper.ensureInitialized();
  p24.OneMapper.ensureInitialized();
  p24.TwoMapper.ensureInitialized();
  p25.ShepherdMapper.ensureInitialized();
  p25.AnimalMapper.ensureInitialized();
  p25.CatMapper.ensureInitialized();
  p25.SiameseMapper.ensureInitialized();
  p25.DogMapper.ensureInitialized();
  p25.HumanMapper.ensureInitialized();
  p26.AnimalMapper.ensureInitialized();
  p26.CatMapper.ensureInitialized();
  p26.DogMapper.ensureInitialized();
  p26.NullAnimalMapper.ensureInitialized();
  p26.DefaultAnimalMapper.ensureInitialized();
  p26.ZooMapper.ensureInitialized();
  p27.ItemsMapper.ensureInitialized();
  p27.ItemMapper.ensureInitialized();
  p28.LocationMapper.ensureInitialized();
  p29.AMapper.ensureInitialized();
  p29.CMapper.ensureInitialized();
  p30.AMapper.ensureInitialized();
  p30.BMapper.ensureInitialized();
  p31.AMapper.ensureInitialized();
  p31.BMapper.ensureInitialized();
  p32.AMapper.ensureInitialized();
  p32.BMapper.ensureInitialized();
  p32.CMapper.ensureInitialized();
  p33.PersonMapper.ensureInitialized();
  p33.CarMapper.ensureInitialized();
  p33.BrandMapper.ensureInitialized();
  p34.AMapper.ensureInitialized();
  p34.BMapper.ensureInitialized();
  p34.CMapper.ensureInitialized();
}
