// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element

import '../../example/lib/main.dart' as p0;
import '../copy_with/copy_with_data_test.dart' as p1;
import '../copy_with/copy_with_subtype_test.dart' as p2;
import '../copy_with/copy_with_test.dart' as p3;
import '../custom_mapper/custom_mapper_test.dart' as p4;
import '../enums/enum_map_test.dart' as p5;
import '../enums/enums_test.dart' as p6;
import '../external_types/external_types_test.dart' as p7;
import '../generics/duplicate_names_test.dart' as p8;
import '../generics/generics_change_test.dart' as p9;
import '../generics/generics_test.dart' as p10;
import '../hooks/hooks_test.dart' as p11;
import '../polymorphism/custom_discriminator_test.dart' as p14;
import '../polymorphism/mixed_mappable_test.dart' as p15;
import '../polymorphism/multi_poly_test.dart' as p16;
import '../polymorphism/polymorphism_test.dart' as p17;
import '../primitives/primitives_test.dart' as p18;
import '../selective_generation/selective_generation_test.dart' as p19;
import '../serialization/basic_serialization_test.dart' as p20;
import '../serialization/nested_serialization_test.dart' as p21;
import 'init_lib_test.dart' as p12;
import 'models/model.dart' as p13;

void initializeMappers() {
  p0.PersonMapper.ensureInitialized();
  p0.CarMapper.ensureInitialized();
  p0.BoxMapper.ensureInitialized();
  p0.ConfettiMapper.ensureInitialized();
  p0.BrandMapper.ensureInitialized();
  p1.AMapper.ensureInitialized();
  p1.BMapper.ensureInitialized();
  p2.AnimalMapper.ensureInitialized();
  p2.CatMapper.ensureInitialized();
  p2.DogMapper.ensureInitialized();
  p2.ZooMapper.ensureInitialized();
  p2.AMapper.ensureInitialized();
  p2.CMapper.ensureInitialized();
  p2.BMapper.ensureInitialized();
  p3.PersonMapper.ensureInitialized();
  p3.CarMapper.ensureInitialized();
  p3.BrandMapper.ensureInitialized();
  p3.DealershipMapper.ensureInitialized();
  p3.ItemListMapper.ensureInitialized();
  p3.BrandListMapper.ensureInitialized();
  p3.NamedItemListMapper.ensureInitialized();
  p3.KeyedItemListMapper.ensureInitialized();
  p3.ComparableItemListMapper.ensureInitialized();
  p4.TestObjMapper.ensureInitialized();
  p5.ClassAMapper.ensureInitialized();
  p5.EnumAMapper.ensureInitialized();
  p6.StateMapper.ensureInitialized();
  p6.ColorMapper.ensureInitialized();
  p6.ItemsMapper.ensureInitialized();
  p6.StatusMapper.ensureInitialized();
  p7.PersonMapper.ensureInitialized();
  p8.BoxMapper.ensureInitialized();
  p8.ContentMapper.ensureInitialized();
  p9.AMapper.ensureInitialized();
  p9.BMapper.ensureInitialized();
  p9.CMapper.ensureInitialized();
  p9.DMapper.ensureInitialized();
  p9.EMapper.ensureInitialized();
  p10.BoxMapper.ensureInitialized();
  p10.ConfettiMapper.ensureInitialized();
  p10.ContentMapper.ensureInitialized();
  p10.DataMapper.ensureInitialized();
  p10.SingleSettingMapper.ensureInitialized();
  p10.SettingsMapper.ensureInitialized();
  p10.AssetMapper.ensureInitialized();
  p11.GameMapper.ensureInitialized();
  p11.CardGameMapper.ensureInitialized();
  p11.PlayerMapper.ensureInitialized();
  p11.ClothesMapper.ensureInitialized();
  p11.ComponentMapper.ensureInitialized();
  p12.AMapper.ensureInitialized();
  p12.BMapper.ensureInitialized();
  p13.AMapper.ensureInitialized();
  p14.AMapper.ensureInitialized();
  p14.BMapper.ensureInitialized();
  p14.CMapper.ensureInitialized();
  p15.BaseMapper.ensureInitialized();
  p15.OneMapper.ensureInitialized();
  p15.TwoMapper.ensureInitialized();
  p16.AnimalMapper.ensureInitialized();
  p16.CatMapper.ensureInitialized();
  p16.SiameseMapper.ensureInitialized();
  p16.DogMapper.ensureInitialized();
  p16.ShepherdMapper.ensureInitialized();
  p17.AnimalMapper.ensureInitialized();
  p17.CatMapper.ensureInitialized();
  p17.DogMapper.ensureInitialized();
  p17.NullAnimalMapper.ensureInitialized();
  p17.DefaultAnimalMapper.ensureInitialized();
  p17.ZooMapper.ensureInitialized();
  p18.ItemsMapper.ensureInitialized();
  p18.ItemMapper.ensureInitialized();
  p19.AMapper.ensureInitialized();
  p19.BMapper.ensureInitialized();
  p20.AMapper.ensureInitialized();
  p20.BMapper.ensureInitialized();
  p21.PersonMapper.ensureInitialized();
  p21.CarMapper.ensureInitialized();
  p21.BrandMapper.ensureInitialized();
}
